remote_theme:     sighingnow/jekyll-gitbook
title:            Vicki Langer Devs Stuff
description:      Bookmark me to keep an eye on Vicki's project updates!
timezone:         America/New_York
encoding:         utf-8
